name: Pre-commit Checks

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    pre-commit:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.ah okx

            - name: npm install
              run: npm install
            - name: npx prettier .
              run: npx prettier .
